const blogPosts = [
  {
    id: 1,
    title: "A Dreamy Beachside Wedding in Bali",
    image: "/images/13.webp",
    author: "Elena Rodriguez",
    date: "March 15, 2024",
  },
  {
    id: 2,
    title: "Rustic Vineyard Elopement in Napa Valley",
    image: "/images/14.webp",
    author: "Michael Chen",
    date: "February 28, 2024",
  },
  {
    id: 3,
    title: "Garden Party Wedding in Charleston",
    image: "/images/15.webp",
    author: "Sarah Thompson",
    date: "April 5, 2024",
  },
  {
    id: 4,
    title: "Mountain Lodge Winter Wedding",
    image: "/images/a.webp",
    author: "David Park",
    date: "January 20, 2024",
  },
  {
    id: 5,
    title: "Urban Rooftop Romance in New York",
    image: "/images/b11.webp",
    author: "Jessica Liu",
    date: "May 12, 2024",
  },
  {
    id: 6,
    title: "Tropical Paradise Wedding in Hawaii",
    image: "/images/c11.webp",
    author: "Ryan Johnson",
    date: "June 8, 2024",
  },
  {
    id: 6,
    title: "Tropical Paradise Wedding in Hawaii",
    image: "/images/c111.webp",
    author: "Ryan Johnson",
    date: "June 8, 2024",
  },
  {
    id: 6,
    title: "Tropical Paradise Wedding in Hawaii",
    image: "/images/d1.webp",
    author: "Ryan Johnson",
    date: "June 8, 2024",
  },
  {
    id: 6,
    title: "Tropical Paradise Wedding in Hawaii",
    image: "/images/d11.webp",
    author: "Ryan Johnson",
    date: "June 8, 2024",
  },
  {
    id: 1,
    title: "A Dreamy Beachside Wedding in Bali",
    image: "/images/13.webp",
    author: "Elena Rodriguez",
    date: "March 15, 2024",
  },
  {
    id: 2,
    title: "Rustic Vineyard Elopement in Napa Valley",
    image: "/images/14.webp",
    author: "Michael Chen",
    date: "February 28, 2024",
  },
  {
    id: 3,
    title: "Garden Party Wedding in Charleston",
    image: "/images/15.webp",
    author: "Sarah Thompson",
    date: "April 5, 2024",
  },
  {
    id: 4,
    title: "Mountain Lodge Winter Wedding",
    image: "/images/d111.webp",
    author: "David Park",
    date: "January 20, 2024",
  },
  {
    id: 5,
    title: "Urban Rooftop Romance in New York",
    image: "/images/c11.webp",
    author: "Jessica Liu",
    date: "May 12, 2024",
  },
  {
    id: 6,
    title: "Tropical Paradise Wedding in Hawaii",
    image: "/images/d.webp",
    author: "Ryan Johnson",
    date: "June 8, 2024",
  },
  {
    id: 1,
    title: "A Dreamy Beachside Wedding in Bali",
    image: "/images/13.webp",
    author: "Elena Rodriguez",
    date: "March 15, 2024",
  },
  {
    id: 2,
    title: "Rustic Vineyard Elopement in Napa Valley",
    image: "/images/14.webp",
    author: "Michael Chen",
    date: "February 28, 2024",
  },
  {
    id: 3,
    title: "Garden Party Wedding in Charleston",
    image: "/images/15.webp",
    author: "Sarah Thompson",
    date: "April 5, 2024",
  },
  {
    id: 4,
    title: "Mountain Lodge Winter Wedding",
    image: "/images/d111.webp",
    author: "David Park",
    date: "January 20, 2024",
  },
  {
    id: 5,
    title: "Urban Rooftop Romance in New York",
    image: "/images/c11.webp",
    author: "Jessica Liu",
    date: "May 12, 2024",
  },
  {
    id: 6,
    title: "Tropical Paradise Wedding in Hawaii",
    image: "/images/d.webp",
    author: "Ryan Johnson",
    date: "June 8, 2024",
  },
  {
    id: 6,
    title: "Tropical Paradise Wedding in Hawaii",
    image: "/images/a11.webp",
    author: "Ryan Johnson",
    date: "June 8, 2024",
  },
  {
    id: 6,
    title: "Tropical Paradise Wedding in Hawaii",
    image: "/images/a111.webp",
    author: "Ryan Johnson",
    date: "June 8, 2024",
  },
  {
    id: 6,
    title: "Tropical Paradise Wedding in Hawaii",
    image: "/images/a1111.webp",
    author: "Ryan Johnson",
    date: "June 8, 2024",
  },

  {
    id: 1,
    title: "A Dreamy Beachside Wedding in Bali",
    image: "/images/13.webp",
    author: "Elena Rodriguez",
    date: "March 15, 2024",
  },
  
];

export default blogPosts;
